name 'noonie2k-php'
version '0.2.0'
source 'git://github.com/noonie2k/puppet-php.git'
author 'noonie2k'
license 'Apache 2.0'
summary 'Puppet module for php'
description 'Module for php configuration'
project_page 'https://github.com/noonie2k/puppet-php'
