name 'jonono-php'
version '0.1.2'
source 'git://github.com/jonono/puppet-php.git'
author 'jonono'
license 'Apache 2.0'
summary 'Puppet module for php'
description 'Module for php configuration'
project_page 'https://github.com/jonono/puppet-php'
dependency 'jonono/puppet-pear', '>= 0'
